config/routes.rb
Claims::Application.routes.draw do

  authenticated :user do
    root to: 'products#index'
  end
  root to: "home#index"
  devise_for :users, path_prefix: 'd'
  devise_scope :user do
    get "d/users/sign_in" => "users/sessions#new",      as: :new_user_session
    get "d/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
  end
  resources :users, except: [:show, :destroy] do
    put 'status', on: :member
  end
  resources :brands, except: [:show]
  resources :product_types, except: [:show]
  resources :master_claims, except: [:show] do
    member do
      get 'sub_claims'
    end
  end
  resources :sub_claims, except: [:show]
  resources :ingredients, except: [:show] do
    collection do
        get 'image'
     end
  end
  resources :ingredient_classes, except: [:show]
  resources :type_of_studies, except: [:show]
  resources :problem_solutions, except: [:show]
  resources :skin_hair_types, except: [:show]
  resources :formulations, except: [:show]
  resources :rounds, except: [:show]
  resources :type_of_ingredients, except: [:show]
  resources :article_types, except: [:show]
  resources :products, except: [:show] do
    resources :additional_claims do
      collection do
        get "users"
      end
    end
  end

end

app/models/additional_claim.rb
class AdditionalClaim < ActiveRecord::Base
  attr_accessible :allergy_concerns, :answer, :assigned_to, :chemical_info_from_company, :chemical_summary, :claim_type, :copy_assigned_to, :copy_status, :editorial_summary, :master_claim_id, :other_concerns, :product_id, :question, :research_status, :sub_claim_ids

  belongs_to :product
  delegate :name, to: :product, allow_nil: true, prefix: true

  belongs_to :master_claim
  delegate :name, to: :master_claim, allow_nil: true, prefix: true

  belongs_to :assignee, class_name: "User", foreign_key: "assigned_to"
  delegate :name, to: :assignee, allow_nil: true, prefix: true

  belongs_to :editor, class_name: "User", foreign_key: "copy_assigned_to"
  delegate :name, to: :editor, allow_nil: true, prefix: true

  has_many :additional_claim_sub_claims, dependent: :destroy
  has_many :sub_claims, through: :additional_claim_sub_claims

  has_many :reviews, as: :reviewable, dependent: :destroy

  validates :master_claim_id, :claim_type, :research_status, presence: true
  validates :assigned_to, presence: true, if: :status_other_then_unassigned?
  validate :status_is_unassigned
  validates :copy_assigned_to, presence: true, if: :copy_status_other_then_unassigned?
  validate :copy_status_is_unassigned

  scope :include_associated_classes, include: [:sub_claims, :master_claim, :assignee, :editor]
  scope :fetch_chemist_type_claims, where("claim_type = ?", 'Additional Claim-Chemist')
  #scope :paginate_data, lambda{|page_no| paginate(page: page_no, per_page: 1)}

  
  def as_xls(options = {})
    {
      "Claim / Sub Claim" => self.master_claim_name.capitalize + "/" + self.sub_claims.collect(&:name).join(", "),
      "Claim Type" => claim_type,
      "Research Status" => research_status,
      "Assigned To" => self.assignee_name,
      "Modified At" => updated_at.to_s(:full_friendly)
    }
  end

  define_index do
    indexes research_status, claim_type, sortable: true
    indexes master_claim(:name), as: :master_claim, sortable: true    
    #indexes user(:name), as: :assigned_to, sortable: true
    #indexes self.assignee_name
    has product_id, master_claim_id#, assigned_to
    set_property delta: true
  end

  private
  def status_other_then_unassigned?
    !self.research_status.eql?("Unassigned")
  end

  def status_is_unassigned
    if self.assigned_to.present? && self.research_status.eql?("Unassigned")
      errors.add(:research_status, "can't assigned to unassigned additional claim")
    end
  end

  def copy_status_other_then_unassigned?
    !self.copy_status.eql?("Unassigned")
  end

  def copy_status_is_unassigned
    if self.copy_assigned_to.present? && self.copy_status.eql?("Unassigned")
      errors.add(:copy_status, "can't assigned to unassigned additional claim")
    end
  end

end

app/controllers/additional_claims_controller.rb
class AdditionalClaimsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_role, only: [:new, :create]

  def index
    @product            = Product.find(params[:product_id])
    @additional_claims  = @product.fetch_additional_claims(current_user, params)
    
    respond_to do |format|
      format.html
      format.xls { send_data @additional_claims.to_xls, content_type: 'application/vnd.ms-excel', filename: 'additional_claims.xls' }
    end
  end

  def new
    @product           = Product.find(params[:product_id])
    @additional_claim  = @product.additional_claims.new
    @sub_claims        = []
    @assignees         = User.admins
    @editors           = User.admins_and_editors
  end

  def create
    @product = Product.find(params[:product_id])
    @additional_claim = @product.additional_claims.new(params[:additional_claim])
    respond_to do |format|
      if @additional_claim.save
        format.html { redirect_to product_additional_claims_path(@product), notice: 'Additional claim was successfully created.' }
        format.json { render json: @additional_claim, status: :created, location: @additional_claim }
      else
        @sub_claims        = []
        @assignees         = params[:additional_claim][:claim_type].eql?("Additional Claim-Admin") ?  User.admins : User.all_users
        @editors           = User.admins_and_editors
        format.html { render "new" }
        format.json { render json: @additional_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @product           = Product.find(params[:product_id])
    @additional_claim  = AdditionalClaim.find(params[:id])
    collected_instancese
    flash[:notice]     = "Assigne the claim to your self" if @additional_claim.research_status.eql?("Unassigned")
    raise CanCan::AccessDenied unless check_user_accessibility?
  end
    
  def update
    @product           = Product.find(params[:product_id])
    @additional_claim  = AdditionalClaim.find(params[:id])
    respond_to do |format|
      if @additional_claim.update_attributes(params[:additional_claim])
        format.html { redirect_to product_additional_claims_path(@product), notice: "Additional Claim was successfully updated."}
        format.json { head :no_content }
      else
        collected_instancese
        format.html { render "edit" }
        format.json { render json: @additional_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @additional_claim  = AdditionalClaim.find(params[:id])
    @product = @additional_claim.product
  end

  def destroy
    @product            = Product.find(params[:product_id])
    @additional_claim   = AdditionalClaim.find(params[:id])
    @additional_claim.destroy
    redirect_to product_additional_claims_path(@product)
  end

  def users
    @assignees        = User.admins if params[:claim_type].eql?("Additional Claim-Admin")
    @assignees        = User.all_users if params[:claim_type].eql?("Additional Claim-Chemist")
  end

  private
  def check_user_accessibility?
    if current_user.has_role? :admin
      true
    elsif(current_user.has_role? :chemist)
      @additional_claim.claim_type.eql?("Additional Claim-Admin") ? false : true
    elsif(current_user.has_role? :editor)
      true
    end
  end

  def collected_instancese
    @sub_claims        = @additional_claim.master_claim.sub_claims
    @assignees         = User.admins if @additional_claim.claim_type.eql?("Additional Claim-Admin")
    @assignees         = User.all_users if @additional_claim.claim_type.eql?("Additional Claim-Chemist")
    @editors           = User.admins_and_editors
  end

end

app/helpers/additional_claims_helper.rb
module AdditionalClaimsHelper
  def accessibility_conditions(claim)
    if (current_user.has_role?(:admin) || current_user.has_role?(:chemist))
      ((current_user.has_role? :admin) || (claim.assignee_name.eql?(current_user.name)) ||
        claim.research_status.eql?("Unassigned") )
    else
      (claim.editor_name.eql?(current_user.name) || claim.copy_status.eql?("Unassigned") )
    end
  end
end

app/views/additional_claims/_additional_claims.erb
<% additional_claims.each do |additional_claim| %>
  <tr>    
    <td><%= additional_claim.master_claim_name.capitalize %> / <%= additional_claim.sub_claims.collect(&:name).join(", ") %></td>
    <td><%= additional_claim.claim_type %></td>
    <td><%= additional_claim.research_status %></td>
    <td><%= additional_claim.assignee_name %></td>
    <td><%= additional_claim.copy_status %></td>
    <td><%= additional_claim.editor_name %></td>
    <td><%= additional_claim.updated_at.to_s(:full_friendly) %></td>
    <td>
      <%= link_to "View Claim", product_additional_claim_path(product, additional_claim), class: 'btn btn-min btn-primary' %>
      <% if accessibility_conditions(additional_claim) %>
        <%= link_to "Edit", edit_product_additional_claim_path(product, additional_claim), class: 'btn btn-min btn-primary' %>        
      <% end %>
      <%= link_to "Delete", product_additional_claim_path(product, additional_claim), method: "DELETE", confirm: "Are you sure?", class: 'btn btn-min btn-primary' if current_user.has_role? :admin %>
    </td>
   </tr>
<%end%>

app/views/additional_claims/_admin_form.erb
<%= f.association :master_claim, prompt: "Please select Additional Claim", autofocus: true, required: true, input_html: { class: "master_claims_list" }  %>
<div id="master-sub-claims"><%= render "master_claims/sub_claims", sub_claims: sub_claims %></div>
<% selected = params[:additional_claim].present? ? params[:additional_claim][:claim_type] : (additional_claim.blank? ? "Additional Claim-Admin" : additional_claim.claim_type)  %>
<%= f.input :claim_type, collection: (['Additional Claim-Admin', 'Additional Claim-Chemist']), selected: selected , required: true %>
<% selected = params[:additional_claim].present? ? params[:additional_claim][:research_status] : (additional_claim.blank? ? "Unasssigned" : additional_claim.research_status)  %>
<%= f.input :research_status, collection: (allowed_status(additional_claim, current_user)), selected: selected, required: true, input_html: { class: "status-list" } %>
<div id="assignee_users">
  <%= render "users", assignees: assignees, claim: additional_claim %>
</div>
<% selected = params[:additional_claim].present? ? params[:additional_claim][:copy_status] : (additional_claim.blank? ? "Unasssigned" : additional_claim.copy_status)  %>
<%= f.input :copy_status, collection: (allowed_copy_status(additional_claim, current_user)), selected: selected, required: true, input_html: { class: "copy-status-list" } %>
<div id="editor_users">
  <%= render "editors", editors: editors %>
</div>
<%= f.input :chemical_summary, input_html: { class: "tinymce"} %>
<%= f.input :editorial_summary, input_html: { class: "tinymce"} %>
<%= f.input :question, input_html: { class: "tinymce"} %>
<%= f.input :answer, input_html: { class: "tinymce"} %>
<%= f.input :allergy_concerns %>
<%= f.input :other_concerns %>
<%= f.input :chemical_info_from_company %>

app/views/additional_claims/_chemist_unassigned_form.erb
<%= f.input :research_status, collection: (allowed_status(additional_claim, current_user)), required: true, include_blank: false, input_html: { class: "status-list" } %>
<%= hidden_field_tag "additional_claim[assigned_to]", current_user.id %>

app/views/additional_claims/_editor_form.erb
<% selected = params[:additional_claim].present? ? params[:additional_claim][:copy_status] : (additional_claim.blank? ? "Unasssigned" : additional_claim.copy_status)  %>
<%= f.input :copy_status, collection: (allowed_copy_status(additional_claim, current_user)), selected: selected, required: true, input_html: { class: "copy-status-list" } %>
<div id="editor_users">
  <%= render "editors", editors: editors, claim: additional_claim %>
</div>
<% if additional_claim.editor.eql?(current_user) && !additional_claim.copy_status.eql?("Unassigned") %>
  <%= f.input :question, input_html: { class: "tinymce"} %>
  <%= f.input :answer, input_html: { class: "tinymce"} %>
<% end %>

app/views/additional_claims/_editors.erb
<div class="control-group select optional">
 <label for="additional_claim_editor" class="select optional control-label"> Editor </label>
 <div class="controls">
  <%= collection_select :additional_claim, :copy_assigned_to, current_user.has_role?(:admin) ?
    editors : claim.editor ? editors.select{|editor| editor.eql?(claim.editor)}  : editors.select{|editor| editor.eql?(current_user)}, :id, :name, {include_blank: true, prompt: "Please select editor"}, {class: "select optional editor_users_list"} %>
 </div>
</div>

app/views/additional_claims/_form.erb
<%= simple_form_for([product, additional_claim], html: {class: 'form-vertical' }) do |f| %>
  <%= f.error_notification %>
  <% if current_user.has_role? :editor%>
    <%= render partial: "editor_form", locals: {f: f, additional_claim: additional_claim, editors: editors} %>
  <% elsif  (additional_claim.assignee_name.eql?(current_user.name)) || (current_user.has_role? :admin) || !additional_claim.research_status.eql?("Unassigned") %>
    <%= render partial: "admin_form", locals: {f: f, sub_claims: sub_claims, additional_claim: additional_claim, assignees: assignees, editors: editors} %>
  <% elsif additional_claim.research_status.eql?("Unassigned") %>
    <%= render partial: "chemist_unassigned_form", locals: {f: f, additional_claim: additional_claim} %>
  <% end %>
  <%= f.button :submit, class: 'btn-primary' %>
  <%= link_to "Cancel", product_additional_claims_path(product) %>
  <%= tinymce %>
<% end %>
<script>
  change_user_label($(".users_list"),$(".status-list"),'Assignee');
  change_user_label($(".editor_users_list"),$(".copy-status-list"),'Editor');
</script>

app/views/additional_claims/_users.erb
<div class="control-group select optional">
 <label for="additional_claim_assignee" class="select optional control-label"> Assignee </label>
 <div class="controls">
  <%= collection_select :additional_claim, :assigned_to, current_user.has_role?(:admin) ?
    assignees : claim.assignee ? assignees.select{|assignee| assignee.eql?(claim.assignee)}  : assignees.select{|assignee| assignee.eql?(current_user)}, :id, :name, {include_blank: true, prompt: "Please select assignee"}, {class: "select optional users_list"} %>
 </div>
</div>

app/views/additional_claims/edit.erb
<fieldset>
  <legend>
    Edit Additional Claim for <a data-toggle="modal" href="#product-description"><%= @product.name.capitalize %></a> Product
   <%= render "shared/product_description", product: @product %>
    <div class="right-align">Add Articles</div>
  </legend>
  <%= render "form", additional_claim: @additional_claim, product: @product, sub_claims: @sub_claims, assignees: @assignees, editors: @editors %>
</fieldset>

app/views/additional_claims/index.html.erb
<div align="right">
  <% if current_user.has_role? :admin %>
    <%= link_to('Add New Additional Claim', new_product_additional_claim_path(@product)) %> |
  <% end %>
  <%= link_to('Export To Excel', product_additional_claims_path(request.parameters.merge({format: :xls}))) %>
</div>
<div align="left">
<%= generate_search_form({index_path: product_additional_claims_path(@product), placeholder: params[:search] ? params[:search] : "Search Additional Claims" }) %>
</div>
<fieldset>
  <legend> Additional Claims List for <a data-toggle="modal" href="#product-description"><%= @product.name.capitalize %></a> product </legend>
  <%= render "shared/product_description", product: @product %>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Claim / Sub Claims</th>
        <th>Claim Type</th>
        <th>Research Status</th>
        <th>Assigned To</th>
        <th>Copy Status</th>
        <th>Editor</th>
        <th>Modified At</th>
        <th data-sorter="false">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render "additional_claims", additional_claims: @additional_claims, product: @product %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"><%= pluralize(@additional_claims.size, 'additional claim') %></td>
      </tr>
    </tfoot>
  </table>
  <%= will_paginate @additional_claims %>
</fieldset>

app/views/additional_claims/new.erb
<fieldset>
  <legend> 
    Create Additional Claim for <a data-toggle="modal" href="#product-description"><%= @product.name.capitalize %></a> Product
   <%= render "shared/product_description", product: @product %>
  </legend>
  <%= render "form", additional_claim: @additional_claim, product: @product, sub_claims: @sub_claims, assignees: @assignees, editors: @editors %>
</fieldset>

app/views/additional_claims/show.erb
<div align="right">
  <% if accessibility_conditions(@additional_claim) %>
    <%= link_to "Edit", edit_product_additional_claim_path(@product, @additional_claim), class: 'btn btn-min btn-primary' %>
  <% end %>
  <%= link_to "Delete", product_additional_claim_path(@product, @additional_claim), method: "DELETE", confirm: "Are you sure?", class: 'btn btn-min btn-primary' if current_user.has_role? :admin %>
  <%= link_to "Back", product_additional_claims_path(@product), class: 'btn btn-min btn-primary'%>
</div>
<h4> Additional Claim Details </h4>
<%= render "shared/product_description", product: @product %>
<table class="table table-condensed">    
  <tbody>
    <tr>
      <th> Product </th>
      <td> <a data-toggle="modal" href="#product-description"><%= @product.name.capitalize %></a> </td>
    </tr>
    <tr>
      <th> Claim / Sub-claim </th>
      <td> <%= @additional_claim.master_claim_name.capitalize %> / <%= @additional_claim.sub_claims.collect(&:name).join(", ") %> </td>
    </tr>
    <tr>
      <th> Research Status </th>
      <td> <%= @additional_claim.research_status %> </td>
    </tr>
    <tr>
      <th> Assignee </th>
      <td> <%= @additional_claim.assignee_name %> </td>
    </tr>
    <tr>
      <th> Copy Status </th>
      <td> <%= @additional_claim.copy_status %> </td>
    </tr>
    <tr>
      <th> Editor </th>
      <td> <%= @additional_claim.editor_name %> </td>
    </tr>
    <tr>
      <th> Modified at </th>
      <td> <%= @additional_claim.updated_at.to_s(:full_friendly) %> </td>
    </tr>
  </tbody>
</table>

app/views/additional_claims/users.js.erb
$("#assignee_users").html("<%= escape_javascript render("users", assignees: @assignees  ) %>");