config/routes.rb
Claims::Application.routes.draw do

  authenticated :user do
    root to: 'products#index'
  end
  root to: "home#index"
  devise_for :users, path_prefix: 'd'
  devise_scope :user do
    get "d/users/sign_in" => "users/sessions#new",      as: :new_user_session
    get "d/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
  end
  resources :users, except: [:show, :destroy] do
    put 'status', on: :member
  end
  resources :brands, except: [:show]
  resources :product_types, except: [:show]
  resources :master_claims, except: [:show] do
    member do
      get 'sub_claims'
    end
  end
  resources :sub_claims, except: [:show]
  resources :ingredients, except: [:show] do
    collection do
        get 'image'
     end
  end
  resources :ingredient_classes, except: [:show]
  resources :type_of_studies, except: [:show]
  resources :problem_solutions, except: [:show]
  resources :skin_hair_types, except: [:show]
  resources :formulations, except: [:show]
  resources :rounds, except: [:show]
  resources :type_of_ingredients, except: [:show]
  resources :article_types, except: [:show]
  resources :products, except: [:show] do
    resources :additional_claims do
      collection do
        get "users"
      end
    end
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :avatar1, :avatar2, :avatar3, :ingredient, :ingredient_definition, :latin_name
  mount_uploader :avatar1, ImageUploader
  mount_uploader :avatar2, ImageUploader
  mount_uploader :avatar3, ImageUploader

  validates :ingredient, presence: true, uniqueness: {case_sensitive: false}

  def as_xls(options = {})
    {
      "Ingredient" => ingredient,
      "Latin Name" => latin_name,
      "Ingredient Definition" => ingredient_definition
    }
  end

  def images?
    return (self.avatar1? || self.avatar2? || self.avatar3?)
  end

  def remove_image(avatar)
    eval("self.remove_avatar#{avatar} = true")
  end

  define_index do
    indexes ingredient, sortable: true
    indexes latin_name, sortable: true
    indexes ingredient_definition, sortable: true
    set_property delta: true
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :authenticate_user!, :authorize_role, :fetch_ingredient

  def index
    @ingredients = params[:search] ? Ingredient.search(params[:search], star: true).paginate(page: params[:page], per_page: 10) : Ingredient.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.xls { send_data @ingredients.to_xls, content_type: 'application/vnd.ms-excel', filename: 'ingredients.xls' }
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])
    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredients_path, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    @ingredient.remove_image(params[:remove_image]) if params[:remove_image].present?
    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to ingredients_path, notice: "Ingredient was successfully updated."}
        format.json { head :no_content }
      else
        format.html { render "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ingredient.destroy
    respond_to do |format|
     format.html { redirect_to ingredients_path, notice: "Ingredient was successfully deleted."}
    end
  end

  private
  def fetch_ingredient
    @ingredient = Ingredient.find(params[:id]) if params[:id]
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.erb
<%= simple_form_for(ingredient, html: {class: 'form-vertical', multipart: true }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :ingredient, autofocus: true, required: true %>
  <%= f.input :latin_name %>
  <%= label_tag "Image1" %>
  <%= f.file_field :avatar1 %><br/><br/>
  <%= label_tag "Image2" %>
  <%= f.file_field :avatar2 %><br/><br/>
  <%= label_tag "Image3" %>
  <%= f.file_field :avatar3 %><br/><br/>
  <%= f.input :ingredient_definition %>
  <%= f.button :submit, class: 'btn-primary' %>
  <%= link_to "Cancel", ingredients_path %>
<% end %>

app/views/ingredients/_ingredient.erb
<div id="ingredient-images-<%= ingredient.id %>" class="modal" style="display: none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&#215;</a>
    <h3>Images</h3>
  </div>
  <div align="justify">
    &nbsp;<%= link_to "Image1", "javascript:void(0)", {image_id: "1", class: "image-link"} if ingredient.avatar1? %>
    &nbsp;<%= link_to "Image2", "javascript:void(0)", {image_id: "2", class: "image-link"} if ingredient.avatar2? %>
    &nbsp;<%= link_to "Image3", "javascript:void(0)", {image_id: "3", class: "image-link"} if ingredient.avatar3? %>
  </div>
  <% if ingredient.avatar1? %>
    <div id="outer-image1" class="outer-image">
      <%= generate_image_data(ingredient_path(ingredient), ingredient, 1) %>
    </div>
  <% end %>
  <% if ingredient.avatar2? %>
  <div id="outer-image2" class="outer-image" style = "<%= ingredient.avatar1? ? "display:none" : "display:block"%>" >
      <%= generate_image_data(ingredient_path(ingredient), ingredient, 2) %>
    </div>
  <% end %>
  <% if ingredient.avatar3? %>
    <div id="outer-image3" class="outer-image" style = "<%= ingredient.avatar1? || ingredient.avatar2? ? "display:none" : "display:block"%>" >
      <%= generate_image_data(ingredient_path(ingredient), ingredient, 3) %>
    </div>
  <% end %>
</div>

app/views/ingredients/_ingredients.erb
<% ingredients.each do |ingredient| %>
<tr>
 <td width="30%"><%= ingredient.ingredient %></td>
 <td width="15%"><%= ingredient.latin_name %></td>
 <td width="30%"><%= ingredient.ingredient_definition %></td>
 <td width="25%">
  <%= generate_edit_delete_link({object: ingredient, path_value: edit_ingredient_path(ingredient)}) %>
  <% if ingredient.images? %>
   <a data-toggle="modal" href="#ingredient-images-<%= ingredient.id %>" class="btn" type="button">Images</a>
    <%= render ingredient %>
  <% end %>
 </td>
</tr>
<% end %>

app/views/ingredients/edit.html.erb
<fieldset>
  <legend> Edit Ingredient </legend>
  <%= render "form", ingredient: @ingredient %>
</fieldset>

app/views/ingredients/index.html.erb
<div align="right">
  <%= generate_common_links({index_path: ingredients_path(request.parameters.merge({format: :xls})), create_path: new_ingredient_path, object: @ingredients, create_text: "Add New Ingredient" }) %>
</div>
<div align="left">
  <%= generate_search_form({index_path: ingredients_path, placeholder: params[:search] ? params[:search] : "Search Ingredients" }) %>
</div>
<fieldset>
  <legend> Ingredients List</legend>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Ingredient</th>
        <th>Latin Name</th>
        <th>Ingredient Definition</th>
        <th data-sorter="false">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render "ingredients", ingredients: @ingredients %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"><%= pluralize(@ingredients.size, 'ingredient') %></td>
      </tr>
    </tfoot>
  </table>
  <%= will_paginate @ingredients %>
</fieldset>

app/views/ingredients/new.html.erb
<fieldset>
  <legend> Create Ingredient </legend>
  <%= render "form", ingredient: @ingredient %>
</fieldset>