config/routes.rb
Claims::Application.routes.draw do

  authenticated :user do
    root to: 'products#index'
  end
  root to: "home#index"
  devise_for :users, path_prefix: 'd'
  devise_scope :user do
    get "d/users/sign_in" => "users/sessions#new",      as: :new_user_session
    get "d/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
  end
  resources :users, except: [:show, :destroy] do
    put 'status', on: :member
  end
  resources :brands, except: [:show]
  resources :product_types, except: [:show]
  resources :master_claims, except: [:show] do
    member do
      get 'sub_claims'
    end
  end
  resources :sub_claims, except: [:show]
  resources :ingredients, except: [:show] do
    collection do
        get 'image'
     end
  end
  resources :ingredient_classes, except: [:show]
  resources :type_of_studies, except: [:show]
  resources :problem_solutions, except: [:show]
  resources :skin_hair_types, except: [:show]
  resources :formulations, except: [:show]
  resources :rounds, except: [:show]
  resources :type_of_ingredients, except: [:show]
  resources :article_types, except: [:show]
  resources :products, except: [:show] do
    resources :additional_claims do
      collection do
        get "users"
      end
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :application_direction, :ingredients, :name, :price, :sku,
                  :brand_id, :product_type_id, :full_name

  before_save :set_full_name

  validates :sku,:ingredients, :name, :price, :brand_id, :product_type_id, presence: true
  validates :price, numericality: true
  validates :sku, uniqueness: {case_sensitive: false}

  belongs_to :brand
  delegate :name, to: :brand, prefix: true, allow_nil: true

  belongs_to :product_type
  delegate :name, to: :product_type, prefix: true, allow_nil: true

  has_many :additional_claims

  def fetch_additional_claims(user, params)
    all_additional_claims = (if user.has_role? :admin
      self.additional_claims
    else
      self.additional_claims.fetch_chemist_type_claims
    end)
    (if params[:search]
      all_additional_claims.search(params[:search], star: true)        
    else      
      all_additional_claims.include_associated_classes
      #product.additional_claims.include_associated_classes.paginate_data(params[:page])
    end).paginate(page: params[:page], per_page: 10)
  end

  def as_xls(options = {})
    {
      "SKU" => sku,
      "Name" => name,
      "Price" => price,
      "Ingredients" => ingredients,
      "Application Direction" => application_direction,
    }
  end

  define_index do
    indexes full_name, name, sku, ingredients, price, sortable: true
    has brand_id, product_type_id
    set_property delta: true
  end

  private
  def set_full_name
    self.full_name = "#{self.sku} - #{self.brand_name} - #{self.name} - #{self.product_type_name}"
  end
  
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, uniqueness: {case_sensitive: false}

  has_many :products, dependent: :destroy

  def as_xls(options = {})
    {
      "Product Type" => name,
    }
  end

  define_index do
    indexes name, sortable: true
    set_property delta: true
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_role, except: [:index]

  def index
    @products = params[:search] ? Product.search(params[:search], star: true).paginate(page: params[:page], per_page: 10) : Product.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.xls { send_data @products.to_xls, content_type: 'application/vnd.ms-excel', filename: 'products.xls' }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    respond_to do |format|
      if @product.save
        flash[:notice]  = 'Product was successfully created.'
        format.html { 
          redirect_to products_path  if params[:claim_type].blank?
          redirect_to new_product_additional_claim_path(@product)  if params[:claim_type].present? && params[:claim_type].eql?("additional")
          redirect_to products_path  if params[:claim_type].present? && params[:claim_type].eql?("label")
          }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_path, notice: "Product was successfully updated."}
        format.json { head :no_content }
      else
        format.html { render "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: "Product was successfully deleted."}
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_choose_claim.erb
<div id="choose-claim" class="modal" style="display: none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&#215;</a>
    <h3>Choose claim to create</h3>
  </div>
  <div class="modal-body">    
    <%= radio_button_tag 'claim_type', 'additional',false, options = {class: "claim-type", radio_type: "additional"} %> Additional Claim <br/>
    <%= radio_button_tag 'claim_type', 'label', false, options = {class: "claim-type", radio_type: "label"} %> Label Claim <br/>
  </div>
  <div class="modal-footer">
    <a class="btn remove-selection" data-dismiss="modal" href="#">Close</a>
  </div>
</div>

app/views/products/_form.erb
<%= simple_form_for(product, html: {class: 'form-vertical product-form' }) do |f| %>
  <%= f.error_notification %>
  <%= hidden_field_tag "claim_type" %>  
  <%= f.input :sku, autofocus: true, required: true %>
  <%= f.input :name, required: true %>
  <%= f.association :brand, required: true, prompt: "Choose a Brand" %>
  <%= f.association :product_type, required: true, prompt: "Choose a Product Type" %>
  <%= f.input :price, required: true %>
  <%= f.input :ingredients, required: true %>
  <%= f.input :application_direction %>
  <%= f.button :submit, class: 'btn-primary' %>
  <a data-toggle="modal" href="#choose-claim" class="btn btn-primary" type="button">Save and choose claim</a>
  <%= render "choose_claim" %>
  <%= link_to "Cancel", products_path %>
<% end %>

app/views/products/_product.erb
<tr>
  <td width="30%"><%= product.full_name %></td>
  <td width="10%"><%= product.sku %></td>
  <td width="5%"><%= product.price %></td>
  <td width="30%"><%= product.ingredients %></td>
  <td width="25%">
    <% if current_user.has_role? :admin %>
      <%= generate_edit_delete_link({object: product, path_value: edit_product_path(product)}) %>
    <% end %>
    <%= link_to "Additional Claims", product_additional_claims_path(product), class: 'btn btn-min btn-primary' %>
  </td>
</tr>

app/views/products/edit.erb
<fieldset>
  <legend> Edit Product </legend>
  <%= render "form", product: @product %>
</fieldset>

app/views/products/index.html.erb
<div align="right">
  <%= generate_common_links({index_path: products_path(request.parameters.merge({format: :xls})), create_path: new_product_path, object: @products, create_text: "Add New Product" }) if current_user.has_role? :admin %>
</div>
<div align="left">
  <%= generate_search_form({index_path: products_path, placeholder: params[:search] ? params[:search] : "Search Products" }) %>
</div>
<fieldset>
  <legend> Products List</legend>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Full Name</th>
        <th>SKU</th>
        <th>Price</th>
        <th>Ingredients</th>
        <th data-sorter="false">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render @products %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"><%= pluralize(@products.size, 'product') %></td>
      </tr>
    </tfoot>
  </table>
  <%= will_paginate @products %>
</fieldset>

app/views/products/new.erb
<fieldset>
  <legend> Create Product </legend>
  <%= render "form", product: @product %>
</fieldset>